/* Generated By:JavaCC: Do not edit this line. CalcparserConstants.java */
package fcalc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcparserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int NUM = 1;
    /**
     * RegularExpression Id.
     */
    int PLUSOP = 2;
    /**
     * RegularExpression Id.
     */
    int MINUSOP = 3;
    /**
     * RegularExpression Id.
     */
    int MULTIOP = 4;
    /**
     * RegularExpression Id.
     */
    int POWEROP = 5;
    /**
     * RegularExpression Id.
     */
    int DIVIDEOP = 6;
    /**
     * RegularExpression Id.
     */
    int OPEN = 7;
    /**
     * RegularExpression Id.
     */
    int CLOSE = 8;
    /**
     * RegularExpression Id.
     */
    int EQUALOP = 9;
    /**
     * RegularExpression Id.
     */
    int VAR = 10;
    /**
     * RegularExpression Id.
     */
    int GLOBALV = 11;
    /**
     * RegularExpression Id.
     */
    int FUNCV = 12;
    /**
     * RegularExpression Id.
     */
    int COMMA = 13;
    /**
     * RegularExpression Id.
     */
    int LF = 14;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "<NUM>",
            "\"+\"",
            "\"-\"",
            "\"*\"",
            "\"^\"",
            "\"/\"",
            "\"(\"",
            "\")\"",
            "\"=\"",
            "<VAR>",
            "<GLOBALV>",
            "<FUNCV>",
            "\",\"",
            "\"\\n\"",
            "\" \"",
            "\"\\r\"",
            "\"\\t\"",
    };

}
